[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "mkdir -p web/sites/default/files",
  "chmod -R 775 web/sites/default/files"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t web"

[variables]
COMPOSER_MEMORY_LIMIT = "-1"
COMPOSER_ALLOW_SUPERUSER = "1"
